# Generated by Django 3.1.2 on 2020-11-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20201029_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelTable(
            name='filemodel',
            table='file_box',
        ),
    ]
